# Generated by Django 5.0.7 on 2024-08-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id_cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_ubicacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario_ptr',
        ),
        migrations.DeleteModel(
            name='Nosotros',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='rol_permiso',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='rol_permiso',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Rol_permiso',
        ),
    ]
