# Generated by Django 5.0.7 on 2024-09-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paginaPetrocentro', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Fotos_nosotros')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
            ],
        ),
        migrations.AddField(
            model_name='rol',
            name='permiso',
            field=models.ManyToManyField(through='users.Rol_permiso', to='users.permisos'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginaPetrocentro.usuario')),
                ('fecha_ingreso', models.DateField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cargo')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ubicacion')),
            ],
            bases=('paginaPetrocentro.usuario',),
        ),
    ]
