# Generated by Django 5.0.7 on 2024-09-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nosotros',
        ),
        migrations.RemoveField(
            model_name='rol_permiso',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='permiso',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.rol'),
        ),
        migrations.RemoveField(
            model_name='rol_permiso',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Rol_permiso',
        ),
    ]
