# Generated by Django 5.1 on 2024-05-24 16:00

from django.db import migrations

def populate_initial_data(apps, schema_editor):
    # Obtener los modelos de las aplicaciones
    Cargo = apps.get_model('users', 'Cargo')
    Ubicacion = apps.get_model('users', 'Ubicacion')
    Rol = apps.get_model('configuracion', 'Rol')

    # Listas de datos a insertar
    CARGOS = [
        "Gerente de Operaciones", "Administrador de Contrato", "Coordinador de Operaciones",
        "Coordinador HSEQ", "Advisor", "Electromecánico", "Instrumentista", "Aprendiz",
        "Operador", "Auxiliar de Well Testing", "Data"
    ]

    UBICACIONES = [
        "Sibate", "Bogota", "Chichimene", "Mocoa", "Meta", "Putumayo"
    ]

    ROLES = [
        "Administrador", "Empleado"
    ]

    # Insertar los datos, evitando duplicados
    for cargo_nombre in CARGOS:
        Cargo.objects.get_or_create(nombre=cargo_nombre)

    for ubicacion_nombre in UBICACIONES:
        Ubicacion.objects.get_or_create(nombre=ubicacion_nombre)

    for rol_nombre in ROLES:
        Rol.objects.get_or_create(nombre=rol_nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]