# Generated by Django 5.0.7 on 2026-03-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_empleado_id_rol'),
        ('users', '0002_populate_data'),
    ]

    operations = [
    ]
