# Generated by Django 5.0.7 on 2026-03-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cargo_nombre_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='reportes_tareas/', verbose_name='Archivo Adjunto'),
        ),
    ]
