# Generated by Django 5.0.7 on 2026-03-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tarea_archivo_adjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('obligatorio_para', models.ManyToManyField(blank=True, related_name='cursos_requeridos', to='users.cargo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCurso',
            fields=[
                ('id_empleado_curso', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados_cursos/')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha en que el certificado expira.', null=True)),
                ('comentarios_revision', models.TextField(blank=True, help_text='Comentarios del administrador en caso de rechazo.', null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.curso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to='users.empleado')),
            ],
            options={
                'verbose_name': 'Curso de Empleado',
                'verbose_name_plural': 'Cursos de Empleados',
                'db_table': 'empleado_curso',
                'unique_together': {('empleado', 'curso')},
            },
        ),
    ]
