# Generated by Django 5.0.7 on 2026-03-16 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_curso_empleadocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empleado', verbose_name='Empleado Asignado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cargo', verbose_name='Cargo Responsable'),
        ),
    ]
