# Generated by Django 5.0.7 on 2026-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tarea_empleado_alter_tarea_id_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='external_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Externa del Curso'),
        ),
    ]
