# Generated by Django 5.0.7 on 2026-03-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_nosotros_options_alter_permisos_options_and_more'),
        ('paginaPetrocentro', '0002_chatmessage'),
        ('users', '0008_curso_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='comentarios_cumplimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de cumplimiento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.rol'),
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('admin_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_responsable', to='paginaPetrocentro.usuario')),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_afectado', to='paginaPetrocentro.usuario')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'db_table': 'log_actividad',
            },
        ),
    ]
