# Generated by Django 5.0.7 on 2026-03-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tarea_comentarios_cumplimiento_alter_empleado_id_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='VIRTUAL', max_length=10, verbose_name='Modalidad'),
        ),
    ]
