# Generated by Django 5.0.7 on 2026-03-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_curso_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='periodicidad',
            field=models.CharField(choices=[('UNICO', 'Único (Una sola vez)'), ('ANUAL', 'Anual (Cada año)'), ('SEMESTRAL', 'Semestral (Cada 6 meses)'), ('MENSUAL', 'Mensual (Cada mes)')], default='UNICO', max_length=20, verbose_name='Periodicidad'),
        ),
    ]
