# Generated by Django 5.0.7 on 2026-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_curso_periodicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar (Solo Presencial)'),
        ),
    ]
