# Generated by Django 5.0.7 on 2026-03-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0002_chatmessage'),
        ('users', '0012_curso_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_respuesta_admin', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='paginaPetrocentro.usuario')),
            ],
            options={
                'db_table': 'mensaje_chat',
                'ordering': ['fecha'],
            },
        ),
    ]
