# Generated by Django 5.0.7 on 2026-04-20 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_mensajechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('hoja_de_vida', models.FileField(help_text='Adjunte su hoja de vida solo en formato PDF', upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje/Presentación')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('cargo_interes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cargo', verbose_name='Cargo de interés')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidato',
            },
        ),
    ]
