# Generated by Django 5.0.7 on 2026-05-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0007_cotizacion'),
        ('users', '0015_categoriainventario_proveedor_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Inventario',
                'verbose_name_plural': 'Categorías de Inventario',
                'db_table': 'inventory_category',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Ítem')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('min_stock', models.IntegerField(default=5, help_text='Alerta cuando el stock sea menor a este valor', verbose_name='Stock Mínimo')),
                ('max_stock', models.IntegerField(default=100, help_text='Capacidad máxima permitida en bodega', verbose_name='Stock Máximo')),
                ('unit_of_measure', models.CharField(default='Unidades', max_length=50, verbose_name='Unidad de Medida')),
                ('location', models.CharField(blank=True, help_text='Ubicación física (Ej: Bodega A, Estante 4)', max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='users.inventorycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada (Compra/Ajuste)'), ('EXIT', 'Salida (Venta/Consumo/Baja)')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.inventoryitem', verbose_name='Ítem')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginaPetrocentro.usuario', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Transacción de Stock',
                'verbose_name_plural': 'Transacciones de Stock',
                'db_table': 'stock_transaction',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='CategoriaInventario',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
