# Generated by Django 5.0.7 on 2026-05-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_inventorycategory_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ubicacion', verbose_name='Base/Sede'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location_detail',
            field=models.CharField(blank=True, help_text='Ej: Bodega A, Estante 4', max_length=100, null=True, verbose_name='Detalle Ubicación'),
        ),
    ]
