# Generated by Django 5.0.7 on 2026-05-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_inventory_transfer_updates'),
    ]

    operations = [
    ]
