# Generated by Django 5.0.7 on 2026-05-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20260522_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada (Compra/Ajuste)'), ('EXIT', 'Salida (Venta/Consumo/Baja)'), ('TRANSFER', 'Traslado entre Bases')], max_length=10, verbose_name='Tipo de Movimiento'),
        ),
    ]
