# Generated by Django 5.0.7 on 2026-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_stocktransaction_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(max_length=50, verbose_name='SKU/Código'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('sku', 'base')},
        ),
    ]
