# Generated by Django 5.0.7 on 2026-05-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0007_cotizacion'),
        ('users', '0020_alter_inventoryitem_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo del Traslado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('destination_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ubicacion', verbose_name='Base Destino')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.inventoryitem', verbose_name='Equipo')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_processed', to='paginaPetrocentro.usuario', verbose_name='Procesado por (Admin)')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='paginaPetrocentro.usuario', verbose_name='Supervisor Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Traslado',
                'verbose_name_plural': 'Solicitudes de Traslado',
                'db_table': 'transfer_request',
            },
        ),
    ]
