# Generated by Django 5.0.7 on 2026-05-25 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_transferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='calibration_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Calibración'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Artículo'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Equipo'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Alto (m)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(default='OPERATIVO', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso (kg)'),
        ),
    ]
