# Generated by Django 5.0.7 on 2026-05-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_inventoryitem_calibration_cost_inventoryitem_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Largo (m)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TAG'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='technical_spec',
            field=models.TextField(blank=True, null=True, verbose_name='Especificación Técnica'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ancho (m)'),
        ),
    ]
