# Generated by Django 5.0.7 on 2026-05-25 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_inventoryitem_brand_inventoryitem_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Equipo de Inventario', 'verbose_name_plural': 'Equipos de Inventario'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Calibración'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturing_quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad Fabricando'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ods_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden ODS'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='rented_quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad Alquilada'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.inventoryitem', verbose_name='Equipo'),
        ),
    ]
