# Generated by Django 5.0.7 on 2026-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada (Compra/Producción)'), ('EXIT', 'Salida (Consumo/Baja/Venta)'), ('TRANSFER', 'Traslado entre Bases'), ('ADJUST_IN', 'Ajuste Positivo (Devolución/Corrección)'), ('ADJUST_OUT', 'Ajuste Negativo (Pérdida/Deterioro/Corrección)')], max_length=10, verbose_name='Tipo de Movimiento'),
        ),
    ]
