# Generated by Django 5.0.7 on 2026-05-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_proveedor_inventoryitem_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Corto (Ej: Proyecto 1)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Nombre Real / Observaciones (Ej: CHIP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'inventory_project',
            },
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada (Compra/Producción)'), ('EXIT', 'Salida (Consumo/Baja/Venta)'), ('RETURN', 'Devolución (Reingreso)'), ('TRANSFER', 'Traslado entre Bases'), ('ADJUST_IN', 'Ajuste Positivo (Corrección)'), ('ADJUST_OUT', 'Ajuste Negativo (Pérdida/Deterioro)')], max_length=10, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='Proyecto'),
        ),
    ]
