# Generated by Django 5.0.7 on 2026-05-29 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_project_alter_stocktransaction_movement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='destination_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='Proyecto Destino'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('sku', 'base', 'project')},
        ),
    ]
