# Generated by Django 5.0.7 on 2026-05-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_transferrequest_destination_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='destination_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_transfers_in', to='users.project', verbose_name='Proyecto Destino'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='origin_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_transfers_out', to='users.project', verbose_name='Proyecto Origen'),
        ),
    ]
