# Generated by Django 5.0.7 on 2026-05-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_stocktransaction_destination_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Mantenimiento'),
        ),
    ]
