# Generated by Django 5.0.7 on 2026-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_inventoryitem_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='incidents',
            field=models.TextField(blank=True, null=True, verbose_name='Novedades de Entrega'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='received_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('COMPLETED', 'Completado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='Estado'),
        ),
    ]
