# Generated by Django 5.0.7 on 2026-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_transferrequest_incidents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('FUERA DE SERVICIO', 'FUERA DE SERVICIO'), ('DADO DE BAJA', 'DADO DE BAJA'), ('ALQUILADO', 'ALQUILADO'), ('VENDIDO', 'VENDIDO')], default='OPERATIVO', max_length=50, verbose_name='Estado'),
        ),
    ]
