# Generated by Django 5.0.7 on 2026-06-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Administrador/Motivo'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_of_measure',
            field=models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('GALONES', 'GALONES'), ('BARRILES', 'BARRILES'), ('LITROS', 'LITROS'), ('METROS', 'METROS'), ('PULGADAS', 'PULGADAS'), ('PIES', 'PIES')], default='UNIDAD', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='destination_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ubicacion', verbose_name='Base Destino'),
        ),
    ]
