# Generated by Django 5.0.7 on 2026-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_transferrequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Lote'),
        ),
    ]
