# Generated by Django 5.0.7 on 2026-06-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_transferrequest_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('FUERA DE SERVICIO', 'FUERA DE SERVICIO'), ('DADO DE BAJA', 'DADO DE BAJA'), ('VENDIDO', 'VENDIDO'), ('EN PROYECTO', 'EN PROYECTO')], default='OPERATIVO', max_length=50, verbose_name='Estado'),
        ),
    ]
