# Generated by Django 5.0.4 on 2024-09-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
