# Generated by Django 5.0.7 on 2026-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'db_table': 'suscriptores',
            },
        ),
    ]
