# Generated by Django 5.0.7 on 2024-09-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelTable(
            name='estado',
            table='usuario_estado',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
