# Generated by Django 5.0.7 on 2026-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0005_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='comentario_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
