# Generated by Django 5.0.7 on 2026-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPetrocentro', '0006_valoracion_comentario_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
