# Generated by Django 5.0.7 on 2024-09-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name': 'Nosotros', 'verbose_name_plural': 'Nosotros'},
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rol_permiso',
            options={'verbose_name': 'Rol_Permiso', 'verbose_name_plural': 'Roles_Permisos'},
        ),
        migrations.AlterModelTable(
            name='nosotros',
            table='nosotros',
        ),
        migrations.AlterModelTable(
            name='permisos',
            table='permisos',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='rol_permiso',
            table='rol_permiso',
        ),
    ]
