# Generated by Django 5.0.7 on 2024-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_suscriptores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscriptores',
            options={'verbose_name': 'Suscriptor', 'verbose_name_plural': 'Suscriptores'},
        ),
        migrations.AddField(
            model_name='post',
            name='empleado',
            field=models.BooleanField(default=False, verbose_name='Empleado'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria_blog',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
        migrations.AlterModelTable(
            name='suscriptores',
            table='Suscriptores',
        ),
    ]
