# Generated by Django 5.0.7 on 2026-03-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_post_descripcion_alter_post_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptores',
        ),
    ]
