# Generated by Django 5.0.7 on 2024-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_suscriptores_options_post_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='empleado',
            field=models.BooleanField(default=False, verbose_name='Empleados/ No Empleados'),
        ),
    ]
